### ISSUE TITLE
Compiler implicitly excludes some directories

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#54]
I had a crash:
`ldgallery-compiler-exe.EXE: ProcessingException "../ozone.example/Japon 2019\JPEG_20190321_072234.jpg" "Invalid marker used"`

Compilation was instantly stopped.
I tested the file, it looks okay in a viewer, but I removed it.
Restarting the compilation (without the rebuild flag), all files are skipped and nothing new get generated. My galerie is not complete.

Note: il est possible que ce soit un problème d'extension. Je viens de remarquer que le pattern d'inclusion des fichiers est case-sensitive, ce qui est problématique.

Edit: pas que.. il manque des répertoires dans ma version finale...

**Comment by pacien** [comment]
@OzoneGrif Please post the tree of the input and output directories as well as the configuration.

**Comment by pacien** [comment]
Turns out that the compiler's implicit exclusion for directories containing a file named `index.html` was the cause of this issue. The goal was to exclude the output directory from the input in the absence of directory exclusion parameters which have been added since then. Solution is to remove this implicit exclusion.
