### ISSUE TITLE
Garbled console output on error

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#56]
```
Generating:     W:/....
allery-compiler-exe.EXE: mGenerating:   W:/www.xxx.info/gallery/thumbnails\yyy.jpg
agick: callPrCopying:   W:/www.xxx.info/gallery/items\yyy.jpg
ocess: does not exist (No such file or directory)
```

The console is mixed-up.

**Comment by pacien** [comment]
It turns out that most terminals are combining the standard output and error streams into one garbled stream. Implementing locks between those two streams wouldn't be a sane thing to do.

However, most shells allow to select and redirect those streams separately. One could for instance filter out status messages by running `ldgallery 1> /dev/null`, only displaying ungarbled errors in the console.

I'll add a FAQ entry about that. It should be enough.
