### ISSUE TITLE
Types "other" should display an icon based on their extension

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#63]
.MOV / .PDF etc, should display the raw file in an iframe. The icon should change depending on their extension.

**Comment by pacien** [comment]
The list of known item formats will grow as we add new handlers to display them.
The "other" fallback type causes the item to simply be offered for download as per #209.
As such, it is reasonable to leave items with this fallback type with a single icon, so that the user expects to land on a generic download page instead of a specific viewer.
